core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

user_bundle:
   resource: "@UsersBundle/Resources/config/routing.yml"
   prefix:   /admin
search:
    path:     /search
    defaults: { _controller: EventBundle:Search:search }
