core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

users:
    resource: "@UsersBundle/Controller/"
    type:     annotation
    prefix:   /

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

user_bundle:
   resource: "@UsersBundle/Resources/config/routing.yml"
   prefix:   /
