admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

users:
    resource: "@UsersBundle/Controller/"
    type:     annotation
    prefix:   /

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

user_bundle:
   resource: "@UsersBundle/Resources/config/routing.yml"
   prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /chef
