core_homepage:
    path: /
    defaults: { _controller: CoreBundle:Default:index }

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

user_bundle:
   resource: "@UsersBundle/Resources/config/routing.yml"
   prefix:   /admin
