# app/config/security.yml
security:
   encoders:
       FOS\UserBundle\Model\UserInterface: sha512

   role_hierarchy:
       ROLE_ADMIN:       ROLE_ADMIN
       ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN

   providers:
       fos_userbundle:
           id: fos_user.user_provider.username

   firewalls:
       main:
           pattern: ^/
           form_login:
               check_path: fos_user_security_check
               login_path: fos_user_security_login
               provider: fos_userbundle
           logout:
               path:    fos_user_security_logout
               target: /
              # provider: fos_userbundle
              # csrf_provider: form.csrf_provider

           anonymous:    true

   access_control:
       - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin/register, role: ROLE_SUPER_ADMIN }
       - { path: ^/admin/resetting, role: ROLE_SUPER_ADMIN }
       - { path: ^/admin/admin/, role: ROLE_SUPER_ADMIN }
       - { path: ^/event, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/event/*, role: ROLE_SUPER_ADMIN }
