event:
    path:     /
    defaults: { _controller: EventBundle:Event:index }
myevent:
    path:     /myevent
    defaults: { _controller: EventBundle:Event:myevent }
event_create:
    path:     admin/create
    defaults: { _controller: EventBundle:Event:create }
event_new:
    path:     admin/new
    defaults: { _controller: EventBundle:Event:new }
event_show:
    path:     /show/{id}
    defaults: { _controller: EventBundle:Event:show }
event_edit:
    path:     admin/{id}/edit
    defaults: { _controller: EventBundle:Event:edit }
event_update:
    path:     admin/{id}/update
    defaults: { _controller: EventBundle:Event:update }
event_delete:
    path:     admin/{id}/delete
    defaults: { _controller: EventBundle:Event:delete }
