event:
    path:     /
    defaults: { _controller: EventBundle:Event:index }
event_create:
    path:     /create
    defaults: { _controller: EventBundle:Event:create }
event_new:
    path:     /new
    defaults: { _controller: EventBundle:Event:new }
event_show:
    path:     /{id}
    defaults: { _controller: EventBundle:Event:show }
event_edit:
    path:     /{id}/edit
    defaults: { _controller: EventBundle:Event:edit }
event_update:
    path:     /{id}
    defaults: { _controller: EventBundle:Event:update }
event_delete:
    path:     /{id}/delete
    defaults: { _controller: EventBundle:Event:delete }
